name: Smiley.sh
description: A very fast SSG script for bloggers. Written in bash with GitHub Actions support.

runs:
  using: 'composite'
  steps:
    - name: build smiley
      shell: bash
      run: |
        echo hi |
        bash smiley.sh |
        git config user.email "actions@github.com" |
        git config user.name "GitHub Actions" |
        git add . |
        git commit -m "automatic build" |
        git push origin

branding:
  icon: box
  color: purple
