name: Smiley.sh
description: A very fast SSG script for bloggers. Written in bash with GitHub Actions support.

runs:
  using: 'composite'
  steps:
    - name: build smiley
      shell: bash
      run: bash smiley.sh
    - name: Configure git email and user
      shell: bash
      run: git config user.email "actions@github.com" |
        git config user.name "GitHub Actions"
    - name: git add
      shell: bash
      run: git add .
    - name: git commit
      shell: bash
      run: git commit -m "automatic build"
    - name: git push origin
      shell: bash
      run: git push origin

branding:
  icon: box
  color: purple
